# Generated by Django 2.2.12 on 2022-06-15 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20220614_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='descricao',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='descrição'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='nivel',
            field=models.IntegerField(verbose_name='nível'),
        ),
    ]
